from __future__ import annotations

import typer

from scripts.argocd import apply_application
from scripts.render_argocd import render_application
from pathlib import Path

from scripts.generate_service import generate_service
from scripts.github import create_repository
from scripts.git import (
    add_remote,
    create_initial_commit,
    initialize_repository,
    push,
)

app = typer.Typer(
    name="platform",
    help="Internal Developer Platform CLI",
)


@app.callback()
def main():
    """Internal Developer Platform CLI."""
    pass



@app.command()
def create_service(
    service_name: str = typer.Argument(...),
    team: str = typer.Option(..., "--team"),
    environment: str = typer.Option(..., "--environment"),
    github_owner: str = typer.Option(..., "--github-owner"),
):
    """Generate and publish a new service."""

    typer.echo("1. Generating service...")

    output_dir = generate_service(
        service_name=service_name,
        team=team,
        environment=environment,
        github_owner=github_owner,
    )

    typer.echo(f"   Generated at {output_dir}")

    typer.echo("2. Creating GitHub repository...")

    repository_url = create_repository(
        repository_name=service_name,
        description=(
            f"{service_name} generated by "
            "the Internal Developer Platform"
        ),
    )

    typer.echo(f"   Repository: {repository_url}")

    typer.echo("3. Initializing Git repository...")

    initialize_repository(output_dir)

    create_initial_commit(output_dir)

    add_remote(
        output_dir,
        repository_url,
    )

    typer.echo("4. Pushing generated service...")

    push(output_dir)

    typer.echo("")
    typer.echo(
        f"Service '{service_name}' created successfully."
    )

    typer.echo("5. Registering application with Argo CD...")

    argocd_manifest = render_application(
        service_name=service_name,
        github_owner=github_owner,
        output=(
            Path("generated")
            / ".argocd"
            / f"{service_name}.yaml"
        ),
    )

    apply_application(argocd_manifest)

    typer.echo(
        f"   Argo CD application '{service_name}' created."
    )


if __name__ == "__main__":
    app()